<?php
global $adminmenu;
$adminmenu=array();
$adminmenu[1]['title'] = _MI_PHPDOC_ADMIN_MENU1;
$adminmenu[1]['icon'] = 'images/admin/wizard.png';
$adminmenu[1]['image'] = 'images/admin/wizard.png';
$adminmenu[1]['link'] = "admin/index.php?op=wizard&fct=project";
$adminmenu[2]['title'] = _MI_PHPDOC_ADMIN_MENU2;
$adminmenu[2]['icon'] = 'images/admin/category.png';
$adminmenu[2]['image'] = 'images/admin/category.png';
$adminmenu[2]['link'] = "admin/index.php?op=list&fct=category";
$adminmenu[3]['title'] = _MI_PHPDOC_ADMIN_MENU3;
$adminmenu[3]['icon'] = 'images/admin/project.png';
$adminmenu[3]['image'] = 'images/admin/project.png';
$adminmenu[3]['link'] = "admin/index.php?op=list&fct=project";
$adminmenu[4]['title'] = _MI_PHPDOC_ADMIN_MENU4;
$adminmenu[4]['icon'] = 'images/admin/file.png';
$adminmenu[4]['image'] = 'images/admin/file.png';
$adminmenu[4]['link'] = "admin/index.php?op=list&fct=file";
$adminmenu[5]['title'] = _MI_PHPDOC_ADMIN_MENU5;
$adminmenu[5]['icon'] = 'images/admin/class.png';
$adminmenu[5]['image'] = 'images/admin/class.png';
$adminmenu[5]['link'] = "admin/index.php?op=list&fct=class";
$adminmenu[6]['title'] = _MI_PHPDOC_ADMIN_MENU6;
$adminmenu[6]['icon'] = 'images/admin/function.png';
$adminmenu[6]['image'] = 'images/admin/function.png';
$adminmenu[6]['link'] = "admin/index.php?op=list&fct=function";
$adminmenu[7]['title'] = _MI_PHPDOC_ADMIN_MENU7;
$adminmenu[7]['icon'] = 'images/admin/variable.png';
$adminmenu[7]['image'] = 'images/admin/variable.png';
$adminmenu[7]['link'] = "admin/index.php?op=list&fct=variable";
$adminmenu[8]['title'] = _MI_PHPDOC_ADMIN_MENU8;
$adminmenu[8]['icon'] = 'images/admin/path.png';
$adminmenu[8]['image'] = 'images/admin/path.png';
$adminmenu[8]['link'] = "admin/index.php?op=list&fct=path";
$adminmenu[9]['title'] = _MI_PHPDOC_ADMIN_MENU9;
$adminmenu[9]['icon'] = 'images/admin/item_digest.png';
$adminmenu[9]['image'] = 'images/admin/item_digest.png';
$adminmenu[9]['link'] = "admin/index.php?op=list&fct=item_digest";
$adminmenu[10]['title'] = _MI_PHPDOC_ADMIN_MENU10;
$adminmenu[10]['icon'] = 'images/admin/permission.png';
$adminmenu[10]['image'] = 'images/admin/permission.png';
$adminmenu[10]['link'] = "admin/index.php?op=list&fct=permissions";
?>